### ISSUE TITLE
Status of Zenodo webhook

### ISSUE THREAD

**Issue by pdaengeli** [cceh/papyri-wl-data#17]
Despite tagging `v23` as a release on Github, the release was not automatically mirrored on Zenodo. If memory serves well, this used to work for `v21` and `v22`.

The [webhook setup](https://github.com/cceh/papyri-wl-data/settings/hooks/13159308) looks ok and the calls return status 202 "accepted". Nevertheless the release on Zenodo had to be created manually this time.

![image](https://user-images.githubusercontent.com/6328618/62416894-5d8b8700-b643-11e9-9763-474afb85a910.png)
---
![image](https://user-images.githubusercontent.com/6328618/62416900-785dfb80-b643-11e9-9b7b-1149f66ffd90.png)
![image](https://user-images.githubusercontent.com/6328618/62416902-827ffa00-b643-11e9-8a3b-90a9f362dd1e.png)

Some checks should be made using the Zenodo sandbox (or some other test setup).

Perhaps this is related to https://github.com/zenodo/zenodo/issues/40.

**Comment by creativeDev6** [comment]
> Despite tagging `v23` as a release on Github, the release was not automatically mirrored on Zenodo. If memory serves well, this used to work for `v21` and `v22`.

For [v24](https://github.com/cceh/papyri-wl-data/releases/tag/v24) this worked now.
